export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Up Learning",
  headLine: "Flexible Learning",
  description: `Get to learn at your pace and in stress free atmosphere, carefully designed to give you the best learning experience`,
  buttonLabel: "Get started",
  imgStart: false,
  img: "/image/going_up.svg",
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Tailored Learning",
  headLine: "Learn New Concept At Faster Rate",
  description: `Learn unfamiliar things using familiar and relatable examples for your quick understanding of new and difficult concept`,
  buttonLabel: "Learn more",
  imgStart: true,
  img: "/image/online_learning.svg",
  alt: "Learning faster",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "team",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Join Our Team",
  headLine: "Our team is fast growing",
  description: `Get to join a fast growing team. Our team is super charged toward delivering the next big innovation in the world`,
  buttonLabel: "Join Now",
  imgStart: false,
  img: "/image/team.svg",
  alt: "Team",
  dark: false,
  primary: false,
  darkText: true,
};
